output_directory: scans
# Scans
max_range: 10.0
num_points: 100
angle_range: 0.785398

# Locations
use_scan_locations: false
scan_locations:
  - theta: 4.75
    position: [0.0, 3]
  - theta: 1.75
    position: [0.0, -3]
  
  - theta: 4.75
    position: [1.6, 3]
  - theta: 1.75
    position: [1.6, -3]

  - theta: 3.15
    position: [5.0, 0]
  - theta: 0
    position: [-3.4, 0]

# Locations alternative
number_of_scans: 2
initial_theta: 1.75
delta_theta: 0
initial_position: [1, -5]
delta_position: [1, 0]

# Scene
scene: 
  - type: "sinusoid"