objective_args:
  scanline_points: 20
  step_size: 0.1
  both_directions: true
  scan_line_factor: 1.0
  scan_point_factor: 1.0
  smoothness_factor: 1.0
  smoothness_derivative_type: "FORWARD" #  FORWARD or UPWIND
  project_derivative: true

map_args:
  num_points: [40, 40]
  min_coords: [-3, -7]
  max_coords: [4, 4]

optimization_args:
  max_iters: 5000
  initial_lambda: 1
  tolerance: 1e-3
  lambda_factor: 1
  visualize: true
  std_out: true

visualization_args:
  show_points: true
  show_normals: true
  output_height: 1000
  output_width: 1000
  clamp_colour_map: true
  min_value: -5
  max_value: 5

general_args:
  from_ground_truth: false
  initial_value: 3
  data_path: ../data/scans # relative to build directory
