objective_args:
  scanline_points: 8
  step_size: 0.1
  both_directions: true
  scan_line_factor: 1.0
  scan_point_factor: 0.5
  smoothness_factor: 0
  smoothness_derivative_type: "FORWARD" #  FORWARD or UPWIND

map_args:
  num_points: [80, 80]
  min_coords: [-3, -7]
  max_coords: [4, 4]

optimization_args:
  max_iters: 5000
  initial_lambda: 1
  tolerance: 1e-3
  lambda_factor: 1
  visualize: true
  std_out: true

visualization_args:
  show_points: true
  show_normals: false
  output_height: 1000
  output_width: 1000

general_args:
  from_ground_truth: true
  initial_value: 3
  data_path: ../data/multiple_rectangle_rotated_scans # relative to build directory
