objective_args:
  scanline_points: 20
  step_size: 0.1
  both_directions: true
  scan_line_factor: 1.0
  scan_point_factor: 1.0
  smoothness_factor: 1.0
  smoothness_derivative_type: "FORWARD" #  FORWARD or UPWIND

map_args:
  num_points: [40, 40]
  min_coords: [-3, -7]
  max_coords: [4, 4]

optimization_args:
  max_iters: 5000
  initial_lambda: 1
  tolerance: 1e-3
  lambda_factor: 1
  visualize: true
  std_out: true

general_args:
  from_ground_truth: false
  initial_value: 3
  data_path: ../data/scans # relative to build directory
