objective_args:
  # Scan points
  scan_point_factor: 1.0
  # Hallucinated points
  scanline_points: 6
  step_size: 0.1
  both_directions: true
  scan_line_factor: 1.0
  # Eikonal
  smoothness_factor: 0.2
  smoothness_derivative_type: "FORWARD" #  FORWARD, CENTRAL or UPWIND
  project_derivative: true
  normal_knn: 7 # Number of neighbours to consider for normal estimation
  normal_search_radius: 0.0 # Radius for normal estimation. If 0, use knn
  # Odometry
  odometry_factor: 1.0

map_args:
  num_points: [100, 100]
  min_coords: [-13, -25]
  max_coords: [27, 10]
optimization_args:
  max_iters: 10
  initial_lambda: 5
  tolerance: 1e-3
  lambda_factor: 0.9

visualization_args:
  initial_visualization: false
  visualize: false
  save_file: true
  show_points: true
  show_normals: false
  show_path: true
  output_height: 1000
  output_width: 1000
  clamp_colour_map: true
  min_value: -10
  max_value: 10
  std_out: true

general_args:
  from_ground_truth: false
  initial_value: 0
  data_path: ../data/intel/ # relative to build directory
  save_results: true
  experiment_name: "intel_inc_10"
